DELETE FROM FILMS_GENRES;
DELETE FROM LIKES;
DELETE FROM FILMS;
DELETE FROM FRIENDS;
DELETE FROM USERS;

ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;

-- DROP TABLE FILMS_GENRES;
-- DROP TABLE LIKES;
-- DROP TABLE FILMS;
-- DROP TABLE FRIENDS;
-- DROP TABLE USERS;
-- DROP TABLE GENRES;
-- DROP TABLE MPA;