INSERT INTO MPA(RATING_ID, RATING_VALUE) VALUES (1, 'G');
INSERT INTO MPA(RATING_ID, RATING_VALUE) VALUES (2, 'PG');
INSERT INTO MPA(RATING_ID, RATING_VALUE) VALUES (3, 'PG-13');
INSERT INTO MPA(RATING_ID, RATING_VALUE) VALUES (4, 'R');
INSERT INTO MPA(RATING_ID, RATING_VALUE) VALUES (5, 'NC-17');

INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (1, 'Комедия');
INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (2, 'Драма');
INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (3, 'Мультфильм');
INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (4, 'Триллер');
INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (5, 'Документальный');
INSERT INTO GENRES(GENRE_ID, GENRE) VALUES (6, 'Боевик');

DELETE FROM MPA;
DELETE FROM GENRES;

